### PR TITLE
make `--completion` exclusive

### PR DESCRIPTION
**Pull request by vic1707**
should fix issue #263

### CODE REVIEW

**Review by djc — APPROVED** [review]
Nice, thanks!

**Comment by djc** [comment]
> should fix issue #263 

Presumably you've actually tested this? 😄

**Comment by vic1707** [comment]
It fixes the crash when executing the command.
I'm trying to see if zsh completion works as intended.

It also only fixes the issue if the proposed change suits your needs 😉

**Comment by vic1707** [comment]
after installing locally
```
root@0cdf82f66231:/app# ~/.cargo/bin/flamegraph --completions zsh
#compdef flamegraph

autoload -U is-at-least

_flamegraph() {
    typeset -A opt_args
    typeset -a _arguments_options
    local ret=1

    if is-at-least 5.2; then
        _arguments_options=(-s -S -C)
    else
        _arguments_options=(-s -C)
    fi

    local context curcontext="$curcontext" state line
    _arguments "${_arguments_options[@]}" \
'-p+[Profile a running process by pid]:PID: ' \
'--pid=[Profile a running process by pid]:PID: ' \
'--completions=[Generate shell completions for the given shell]:SHELL:(bash elvish fish powershell zsh)' \
'-o+[Output file]:OUTPUT:_files' \
'--output=[Output file]:OUTPUT:_files' \
'-F+[Sampling frequency]:FREQUENCY: ' \
'--freq=[Sampling frequency]:FREQUENCY: ' \
'-c+[Custom command for invoking perf/dtrace]:CUSTOM_CMD: ' \
'--cmd=[Custom command for invoking perf/dtrace]:CUSTOM_CMD: ' \
'--notes=[Set embedded notes in SVG]:STRING: ' \
'--min-width=[Omit functions smaller than <FLOAT> pixels]:FLOAT: ' \
'--image-width=[Image width in pixels]:IMAGE_WIDTH: ' \
'--palette=[Color palette]:PALETTE:(hot mem io red green blue aqua yellow purple orange wakeup java perl js rust)' \
'*--skip-after=[Cut off stack frames below <FUNCTION>; may be repeated]:FUNCTION: ' \
'--post-process=[Run a command to process the folded stacks, taking the input from stdin and outputting to stdout]:POST_PROCESS: ' \
'(-p --pid)--perfdata=[]:PERF_FILE:_files' \
'-v[Print extra output to help debug problems]' \
'--verbose[Print extra output to help debug problems]' \
'--open[Open the output .svg file with default program]' \
'--root[Run with root privileges (using \`sudo\`)]' \
'--deterministic[Colors are selected such that the color of a function does not change between runs]' \
'-i[Plot the flame graph up-side-down]' \
'--inverted[Plot the flame graph up-side-down]' \
'--reverse[Generate stack-reversed flame graph]' \
'(--reverse)--flamechart[Produce a flame chart (sort by time, do not merge stacks)]' \
'--ignore-status[Ignores perf'\''s exit code]' \
'--no-inline[Disable inlining for perf script because of performance issues]' \
'-h[Print help]' \
'--help[Print help]' \
'-V[Print version]' \
'--version[Print version]' \
'*::trailing_arguments:' \
&& ret=0
}

(( $+functions[_flamegraph_commands] )) ||
_flamegraph_commands() {
    local commands; commands=()
    _describe -t commands 'flamegraph commands' commands "$@"
}

if [ "$funcstack[1]" = "_flamegraph" ]; then
    _flamegraph "$@"
else
    compdef _flamegraph flamegraph
fi
```
just need to reproduce my zsh env to check if everything is good (doing everything in docker just in case I blow something xD

**Pull request merged**
