### PR TITLE
Cut 0.4

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

**Comment by polyzen** [comment]
Please start flagging tags again so downstream packagers can be notified when following the repo or [Atom feed](https://github.com/flamegraph-rs/flamegraph/releases). Including release notes as you had been doing is also a treat. ^^

**Comment by djc** [comment]
I've pushed tags for 0.3.1 and 0.4.0, and also published some brief changelogs.

**Comment by polyzen** [comment]
Thank you very much.

**Pull request merged**
